### ISSUE TITLE
Process cannot access the file because it is used by another process

### ISSUE THREAD

**Issue by danielmarbach** [chucknorris/dropkick#48] opened 2012-06-14 07:47 UTC
It is really strange. When I run dropkick without any arguments I receive always the following exception:

---

DropkicK v0.4.13.0

---

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Command:     Trace
Environment: LOCAL
Role:        ALL
Server Maps:   '.\settings\LOCAL.servermaps' - Looks Good!
Settings Path: '.\settings\LOCAL.js' - Looks Good!
Looking for deployment dll 'C:\Users\danielmarbach\Documents\visual studio 2010\Projects\Deployment\Deployment2\bin\Debug\20120614-094240675.run.log' at 'C:\Users\danielmarbach\Documents\visual studio 2010\Projects\Deployment\Deployment2\bin\Debug\20120614-094240675.run.log'
System.IO.FileLoadException: The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020)
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at dropkick.Engine.DeploymentFinders.AssemblyWasSpecifiedAssumingOnlyOneDeploymentClass.Find(String assemblyName) in c:\Solutions\dk-fc\product\dropkick\Engine\DeploymentFinders\AssemblyWasSpecifiedAssumingOnlyOneDeploymentClass.cs:line 45
   at dropkick.Engine.DeploymentFinders.SearchesForAnAssemblyNameContainingDeployment.Find(String assemblyName) in c:\Solutions\dk-fc\product\dropkick\Engine\DeploymentFinders\SearchesForAnAssemblyNameContainingDeployment.cs:line 34
   at dropkick.Engine.DeploymentFinders.MultipleFinder.Find(String deployment) in c:\Solutions\dk-fc\product\dropkick\Engine\DeploymentFinders\MultipleFinder.cs:line 25
   at dropkick.Engine.Runner.Deploy(String commandLine) in c:\Solutions\dk-fc\product\dropkick\Engine\Runner.cs:line 66

The assembly is named Deployment.dll. It resides in the same directory as the dk.exe

**Comment by danielmarbach** [comment] 2012-06-14 07:56
It is really strange. When I simply copy the output folder on another machine and execute the dk.exe the exception doesnt occur but then I get the following exception:

---

DropkicK v0.4.13.0

---

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Command:     Trace
Environment: LOCAL
Role:        ALL
Server Maps:   '.\settings\LOCAL.servermaps' - Looks Good!
Settings Path: '.\settings\LOCAL.js' - Looks Good!
Looking for deployment dll 'Deployment.dll' at 'C:\Users\danielmarbach\Documents\Visual Studio 2010\Projects\Deployment\Deployment2\bin\Debug\Deployment.dll'
Deployment Method: 'Specific Assembly Specified'
Deployment Found:  'TheDeployment'
System.ArgumentException: Invalid JSON primitive: .
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeDictionary(Int32 depth)
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
   at Magnum.ValueProviders.JsonValueProvider..ctor(String text) in d:\Development\git-magnum\src\Magnum\ValueProviders\JsonValueProvider.cs:line 37
   at Magnum.Configuration.Internal.ConfigurationBinderConfiguratorImpl.<>c__DisplayClass9.<AddJson>b__8() in d:\Development\git-magnum\src\Magnum\Configuration\Internal\ConfigurationBinderConfiguratorImpl.cs:line 39
   at Magnum.Configuration.Internal.ConfigurationBinderConfiguratorImpl.<CreateBinder>b__e(Func`1 x) in d:\Development\git-magnum\src\Magnum\Configuration\Internal\ConfigurationBinderConfiguratorImpl.cs:line 49
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Magnum.Configuration.Internal.ConfigurationBinderConfiguratorImpl.CreateBinder() in d:\Development\git-magnum\src\Magnum\Configuration\Internal\ConfigurationBinderConfiguratorImpl.cs:line 49
   at Magnum.Configuration.ConfigurationBinderFactory.DefaultFactory(Action`1 configuratorAction) in d:\Development\git-magnum\src\Magnum\Configuration\ConfigurationBinderFactory.cs:line 37
   at Magnum.Configuration.ConfigurationBinderFactory.New(Action`1 configuratorAction) in d:\Development\git-magnum\src\Magnum\Configuration\ConfigurationBinderFactory.cs:line 25
   at dropkick.Settings.ServerMapParser.Parse(FileInfo file) in c:\Solutions\dk-fc\product\dropkick\Settings\ServerMapParser.cs:line 29
   at dropkick.Engine.Runner.Deploy(String commandLine) in c:\Solutions\dk-fc\product\dropkick\Engine\Runner.cs:line 83

The above exception also occurs when I specify the deployment assembly by issuing

dk.exe /deployment:Deployment.dll in the command line

What I did was:

New assembly in .NET 4.0, Nuget download dropkick, changed the code to the following:

```
public class TheDeployment : Deployment<TheDeployment, DeploymentSettings>
{
    public TheDeployment()
    {
        Define(settings =>
        {
            DeploymentStepsFor(Api,
                               s =>
                               {
                                   s.Msmq()
                                       .PrivateQueue(settings.ApiQueue)
                                       .Transactional();

                                   s.Security(o =>
                                   {
                                       o.ForQueue(settings.ApiQueue, oq =>
                                       {
                                           oq.SetSensibleMsmqDefaults();
                                           oq.GrantReadWrite("NT AUTHORITY\\SYSTEM");
                                       });
                                   });
                               });
        });
    }

    public static Role Api { get; set; }
}

public class DeploymentSettings : DropkickConfiguration
{
    public string ApiQueue { get; set; }
}
```

LOCAL.js

{
    ApiQueue : "Foo",
}

LOCAL.servermaps

{
    Api:"127.0.0.1",
}

All edited in VS2010.

**Comment by danielmarbach** [comment] 2012-06-14 08:23
The second exception about JSON. I finally was able to resolve it. There seems to be a VS2010 settings which kills the line endings and formatting of the json documents. When I open the settings only with notepad++ json exception will not happen.

**Comment by drusellers** [comment] 2012-06-14 09:56
Is visual studio open when you run the command? I am curious if VS has a
lock on it.

-d

On Thu, Jun 14, 2012 at 2:47 AM, danielmarbach <
reply@reply.github.com

**Comment by danielmarbach** [comment] 2012-06-14 10:24
That was my first thought also. First I disabled Mighty Moose, didn't work. Then I completely shut down VS2010, didn't work.

**Comment by danielmarbach** [comment] 2012-06-14 10:25
I spotted also a problem with my JSON configuration. If you have only a single entry and a comma at the end the JSON exception occurs. Kinda difficult to spot but my fault

**Comment by ferventcoder** [comment] 2012-06-14 12:42
Look at your folder structure
 'C:\Users\danielmarbach\Documents\visual studio 2010\Projects\Deployment\Deployment2\bin\Debug\20120614-094240675.run.log'

Notice this? **Deployment\Deployment2**

The issue is likely that the folder name is Deployment... it itself already has a lock on the log file and it's trying to use it as the deployment file.  It's the first file the deployment searcher finds.

**Comment by ferventcoder** [comment] 2012-06-14 12:43
In cases where the folder structure already has the name deployment on it, you want to specify your deployment dll. But let's file a separate enhancement/bug request for the assembly searcher to filter the search down to DLLs (I thought it already did this?)

**Comment by ferventcoder** [comment] 2012-06-14 12:48
Just looked at the code base and it appears okay - https://github.com/chucknorris/dropkick/blob/master/product/dropkick/Engine/DeploymentFinders/SearchesForAnAssemblyNameContainingDeployment.cs#L27-30 

What version are you on? If you go to details on the properties of the dk.exe in one of the versions will be the SHA1 commit hash. That's what I'm looking for.

**Comment by ferventcoder** [comment] 2012-06-14 12:52
Think I found it. The issue is fixed in this commit here. https://github.com/chucknorris/dropkick/commit/fc30c2cf606201d673fcf76f81354a4afbac263c#L5L29

Just not sure we've published a new nuget package since.  If you build from source, can you confirm the behavior is different?

**Comment by danielmarbach** [comment] 2012-07-06 20:32
Sorry I haven't had time to go into this. I'll try it out

**Comment by danielmarbach** [comment] 2012-07-06 20:36
With the latest source compiled it works!

**Comment by ferventcoder** [comment] 2012-07-06 21:11
Awesome!

**Closed as completed** 2012-07-09 19:30 UTC
